---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: C0A8012F.k8s.lab/shell-operator/shell-operator:monitor-service
    imagePullPolicy: Always
  serviceAccountName: monitor-services-acc
